# Generated by Django 2.2.4 on 2020-07-10 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('tutor', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=datetime.datetime(2020, 7, 10, 19, 22, 41, 376692))),
                ('class_time', models.TimeField()),
                ('fee', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
