# Generated by Django 2.2.4 on 2020-07-12 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 12, 11, 38, 56, 958122)),
        ),
    ]
