# Generated by Django 2.2.4 on 2020-07-12 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200712_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='class_time',
            field=models.TimeField(default=12),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='duration',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='fee',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 12, 14, 9, 57, 617625)),
        ),
    ]
