# Generated by Django 2.2.4 on 2020-07-17 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200717_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 18, 5, 29, 492352)),
        ),
    ]
